// Code generated by "stringer -type=ExecutionMode --linecomment"; DO NOT EDIT.

package wam

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Run-0]
	_ = x[VerifyAttributes-1]
}

const _ExecutionMode_name = "runverify_attributes"

var _ExecutionMode_index = [...]uint8{0, 3, 20}

func (i ExecutionMode) String() string {
	if i < 0 || i >= ExecutionMode(len(_ExecutionMode_index)-1) {
		return "ExecutionMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExecutionMode_name[_ExecutionMode_index[i]:_ExecutionMode_index[i+1]]
}
