// Code generated by "stringer -type=PairTag -linecomment"; DO NOT EDIT.

package wam

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AssocPair-0]
	_ = x[ListPair-1]
	_ = x[DictPair-2]
}

const _PairTag_name = "assoclistdict"

var _PairTag_index = [...]uint8{0, 5, 9, 13}

func (i PairTag) String() string {
	if i < 0 || i >= PairTag(len(_PairTag_index)-1) {
		return "PairTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PairTag_name[_PairTag_index[i]:_PairTag_index[i+1]]
}
