// Code generated by "stringer -type=UnificationMode"; DO NOT EDIT.

package wam

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Read-0]
	_ = x[Write-1]
}

const _UnificationMode_name = "ReadWrite"

var _UnificationMode_index = [...]uint8{0, 4, 9}

func (i UnificationMode) String() string {
	if i < 0 || i >= UnificationMode(len(_UnificationMode_index)-1) {
		return "UnificationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnificationMode_name[_UnificationMode_index[i]:_UnificationMode_index[i+1]]
}
